### ISSUE TITLE
Plugin binaries are built with Java12 support, but Teamcity supports only 8 and 11

### ISSUE THREAD

**Issue by ZhukovAN** [vasiliy-briginets/teamcity-yandex-agent#11]
Plugin deployment for TC2020 fails with "_java.lang.UnsupportedClassVersionError: jetbrains/buildServer/clouds/yandex/YandexCloudImagesHolder has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0_" error. Looks like this is because Java 12 is not a supported plaform as stated here: https://www.jetbrains.com/help/teamcity/supported-platforms-and-environments.html#TeamCity+Server.
Tested on official Teamcity Docker image started as:
`docker run -d --name dev-teamcity-2020-2-1 -p 8111:8111 jetbrains/teamcity-server:2020.2.1`

**Comment by vasiliy-briginets** [comment]
fixed in release v1.2 - https://github.com/vasiliy-briginets/teamcity-yandex-agent/releases/tag/v1.2

Thank you for this issue!
