### ISSUE TITLE
Plugin binaries are built with Java13 support, but Teamcity supports only 8 and 11

### ISSUE THREAD

**Issue by ghost** [vasiliy-briginets/teamcity-yandex-agent#12]
After plugin installation got error
`Failed to initialize cloud client 'yandex'.yandex/cloud/endpoint/ApiEndpointServiceGrpc has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

Reassembly with JDK 11 required. Looks like you close #11 by chance

**Comment by vasiliy-briginets** [comment]
Hello!
I've checked right now on TeamCity server v.2020.2.4 (build 86063) with plugin v1.2.0 and all works fine. I just run the docker image "jetbrains/teamcity-server" (which is, of course, the last version right now) and install the plugin on the virgin server.
Could you please give me some more information? What is version of the plugin do you use? What is a version of  TeamCity server?

**Comment by Elufimov** [comment]
Hi @vasiliy-briginets 
I did the same:
run teamcity from docker locally `docker run -it -p 8111:8111 jetbrains/teamcity-server:2020.2.4` 
download latest plugin 1.2
upload plugin to teamcity
activate plugin
create new cloud profile
insert key,json
got `yandex/cloud/endpoint/ApiEndpointServiceGrpc has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

**Comment by abix5** [comment]
I have the same problem. When to expect a fix?

**Comment by vasiliy-briginets** [comment]
Hi all, I've made a release which I hope fixed that problem too. I've also checked it by @Elufimov instruction and it works.

You can find new release on this link - https://github.com/vasiliy-briginets/teamcity-yandex-agent/releases/tag/v1.3
