### ISSUE TITLE
Button "Save" not working when I try to add Agent Images

### ISSUE THREAD

**Issue by andrsharov** [vasiliy-briginets/teamcity-yandex-agent#13]
Hi, Vasiliy! 

I try to install your plugin to TeamCity server 2022.04 (build 108502)  (docker installation), plugin was install without errors.

But when I tryed to add Agent Images , i ran into a problem , "Save" button don't working , it was innactive.

Of course, I was I filled all required fields.

How I can to debug problem?

![Add_image_button](https://user-images.githubusercontent.com/44819772/170530397-115ee3e8-5118-4418-8df7-d82700332b2f.png)
![Save_not_working](https://user-images.githubusercontent.com/44819772/170530474-9ef55bd6-ec67-483d-a8f4-d5dd11e25ebb.png)

**Comment by andrsharov** [comment]
Hi, @vasiliy-briginets .

For debug the problem I was open F12 Network Console, and try seen requests/answers. But I nothing don't see. The "Save" button is not active in any cases.
![add_image_0png](https://user-images.githubusercontent.com/44819772/170988644-237da8fc-170d-44dd-aeeb-88121b8ce9ca.png)
![add_image_1png](https://user-images.githubusercontent.com/44819772/170988659-eb40a71c-24f8-47b9-b389-36274e4764c4.png)
![add_image_2png](https://user-images.githubusercontent.com/44819772/170988679-d7a7eb12-66bc-4489-a978-7a7721962106.png)

**Comment by andrsharov** [comment]
Also I was tried to press the button "Save" in the all compatible browsers without success.

**Comment by vasiliy-briginets** [comment]
Hi Andrey!
> Of course, I was I filled all required fields.
Can you please check that "Json private key" is also specified? I see on you screenshot that this field isn't filled

**Comment by andrsharov** [comment]
Hi, @vasiliy-briginets  .  Thanks for your feedback.

First, I try to remove JSON key. And the button "Add image" has become inactive, as in the screenshot below
![image](https://user-images.githubusercontent.com/44819772/171357349-c7032f97-0889-4d8d-94cf-c99cf9fdd5c3.png)

Next, I was uploaded JSON file again , and the button "Add image" has become active again. as in the screenshot below. 
![image](https://user-images.githubusercontent.com/44819772/171357753-1297181a-7e38-4eaf-8023-10f07cef4fd9.png)

I am also attaching the JSON file , without sentensive data (keys and id). Maybe there is a mistake in this file ?
I see a lot string returns in this file `\n` in the keys , maybe I must to delete them ?
```
{
   "id": "********************",
   "service_account_id": "********************",
   "created_at": "2022-05-30T11:01:31.**********",
   "key_algorithm": "RSA_2048",
   "public_key": "-----BEGIN PUBLIC KEY-----\n\n\n\n\n\n\n\n-----END PUBLIC KEY-----\n",
   "private_key": "-----BEGIN PRIVATE KEY-----\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-----END PRIVATE KEY-----\n"
}
```

Also I tried to play with permissions of the service account. I try to set `Editor` and `Admin` roles , but without success. For test purposes I was chosen `Admin` role.

**Comment by vasiliy-briginets** [comment]
It looks correct. Let me try to reproduce, I will check and return with comment

**Comment by vasiliy-briginets** [comment]
Thank you for your issue, I finally found a problem! We forgot to remove some checks on UI:) 
Now it fixed - https://plugins.jetbrains.com/plugin/12619-yandex-cloud-agents/versions/stable/181504

**Comment by andrsharov** [comment]
Hi, @vasiliy-briginets .

Now it looks good. I don`t make full test (with run virtual machines) , but there are no visible errors in UI. 

After some tests, I will give feadback to you later. 

Thank you!

![image](https://user-images.githubusercontent.com/44819772/172056949-1032e77f-d190-40a8-80fa-18820e0c076b.png)
![image](https://user-images.githubusercontent.com/44819772/172056965-7be41451-79f4-4cad-9b88-e723df492142.png)

**Comment by andrsharov** [comment]
Hi, @vasiliy-briginets .

Today we succeed run virtual machines for testing.

P.S: Thank you.
